### ISSUE TITLE
Awesome page not loading on NIT site

### ISSUE THREAD

**Issue by AlanaKaimi** [nativesintech/natives-in-tech#51]
Issue lives here: [https://nativesintech.org/awesome/](url) https://nativesintech.org/awesome/

Error message: Sorry, there was an error: Expected field 'data',[object Response]

(still learning how to contribute, and work with issues, so please let me know if there's a better way to address or collaborate!)

**Comment by arecvlohe** [comment]
Hey, thanks for letting me know! It might be that the API changed in some way so maybe there is not a data field any more. I will dig in and see what I going on. Thanks again!

**Comment by arecvlohe** [comment]
The issue was the query expected the field `membersWithRoles` and not `members`. Therefore, when I make the request I was getting back an object with an `error` field and not a `data` field. So when my decoder tried to decode the `data` field, it couldn't, because it didn't exist! I could be handling errors here better but for now I updated the query and decoder and changed `members` to `membersWithRole`.

**Comment by arecvlohe** [comment]
Fixed in #52

**Comment by arecvlohe** [comment]
@all-contributors please add AlanaKaimi for bug
